# Generated by Django 4.2.2 on 2023-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_matches_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
