# Generated by Django 4.2.2 on 2023-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_matches_match_id_alter_matches_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
