# Generated by Django 4.2.2 on 2023-06-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_deliveries_dimissal_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='dimissal_kind',
            new_name='dismissal_kind',
        ),
    ]
